# -*- coding: utf-8 -*-
"""BavizhevLab1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qvyDEnyNbv7vY43u4fGB9tDe4dx3lrC5
"""

# Создание структуры данных о ценах на товары в магазинах
prices = {
    "Магазин Марген": {"яблоки": 2.5, "бананы": 1.0, "молоко": 1.2},
    "Магазин Солнце": {"яблоки": 2.0, "бананы": 0.8, "молоко": 1.0},
    "Магазин Дэнди": {"яблоки": 2.8, "бананы": 1.2, "молоко": 1.4},
}

# Ввод списка товаров и количества, которое планируется купить
shopping_list = {}
for item in prices["Магазин Марген"].keys():
    quantity = int(input(f"Введите количество {item}: "))
    shopping_list[item] = quantity

# Расчет общей стоимости покупок в каждом магазине
total_costs = {}
for shop, item_prices in prices.items():
    total_cost = sum(item_prices[item] * quantity for item, quantity in shopping_list.items())
    total_costs[shop] = total_cost

# Определение магазина с минимальной стоимостью
cheapest_shop = min(total_costs, key=total_costs.get)

# Вывод результатов
print("Сравнение цен в разных магазинах:")
for shop, total_cost in total_costs.items():
    print(f"{shop}: Общая стоимость - {total_cost} рублей")
print(f"Сэкономьте больше всего, выбрав {cheapest_shop} магазин!")